Incorporated Best Practices
singer-io/tap-yotpo pull request #14
Opened 2021-05-21 11:39 UTC by harshpatel4crest

# Description of change
TDL-13636: Best Practices
- Updated singer-python version from 5.3.3 -> 5.12.1
- Updated pendulum version from 1.2.0 -> 2.1.2
- Changed sandbox -> tap_tester_sandbox
- tap-tester image is up-to-date
- Added all integration test
    - Test Sync Canary
    - Test Discovery Mode
    - Test Start Date
    - Test Pagination (for "reviews" stream)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-05-31 08:52 UTC, dbshah1212 requested changes

2021-05-31 09:12 UTC, harshpatel4crest commented on tests/base.py
> +    #     }
Done

2021-05-31 09:12 UTC, harshpatel4crest commented on tests/base.py
> +    # def expected_pks(self):
Done

2021-06-01 05:12 UTC, dbshah1212 requested changes

2021-06-01 05:12 UTC, dbshah1212 commented on tests/test_yotpo_start_date.py
> +                        self.assertGreaterEqual(self.dt_to_ts(start_date_key_value), (start_date_1_epoch - 30*24*3600) if reduce_epoch else start_date_1_epoch)
Store 30*24*3600 in one variable.

2021-06-01 05:23 UTC, harshpatel4crest commented on tests/test_yotpo_start_date.py
> +                        self.assertGreaterEqual(self.dt_to_ts(start_date_key_value), (start_date_1_epoch - 30*24*3600) if reduce_epoch else start_date_1_epoch)
Okay

2021-06-01 15:04 UTC, KAllan357 approved these changes

2021-06-01 15:05 UTC, merged