tap-yotpo : Production issue fixes
singer-io/tap-yotpo pull request #41
Opened 2022-07-26 14:55 UTC by rdeshmukh15

# Description of change
Provided fixes for the following tickets :
- [TDL-19836] : Fix transform issue in Products schema
- [TDL-19968] : Table field selection is not working
- [TDL-19839] : Fix Http Error Code – 404 (related to scientific notation product_id. Fixture – Log the warning)
- Added the unit test cases for the same

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

Co-author @sgandhi1311

2022-07-26 15:36 UTC, luandy64 requested changes
There's a lot of changes I'd like to see implemented.

Can we also update the README to update the link for the Products stream? The current link points to http://apidocs.yotpo.com/reference#draft-retrieve-all-products, but the docs are actually at https://core-api.yotpo.com/v1.0/reference/retrieve-all-products

2022-07-26 15:36 UTC, luandy64 commented on tests/unittests/test_stream_changes.py
> +    def test_sync_of_paginated_class_with_unsubscribe_data_with_empty_id(self,mock_transform, mock_on_batch_complete,mock_records_with_empty_id,mock_get_params, mock_to_map):
Especially since you did it down below on line 39

2022-07-26 15:36 UTC, luandy64 commented on tests/unittests/test_data_transforming.py
> +        self.assertEqual(transform_error, True, "Exception raised")
Here are 170 examples form 26 different taps to follow
https://sourcegraph.com/search?q=context:global+repo:singer-io/*+assertRaises+lang:python+count:1000&patternType=structural

2022-07-27 10:40 UTC, rdeshmukh15 commented
> There's a lot of changes I'd like to see implemented.
> 
> Can we also update the README to update the link for the Products stream? The current link points to http://apidocs.yotpo.com/reference#draft-retrieve-all-products, but the docs are actually at https://core-api.yotpo.com/v1.0/reference/retrieve-all-products

Done

2022-07-27 10:41 UTC, rdeshmukh15 commented on tests/unittests/test_stream_changes.py
> +    def test_sync_of_paginated_class_with_unsubscribe_data_with_empty_id(self,mock_transform, mock_on_batch_complete,mock_records_with_empty_id,mock_get_params, mock_to_map):
Removed the extra spaces added. From Line No. 39 as well.

2022-07-27 10:43 UTC, rdeshmukh15 commented on tests/unittests/test_data_transforming.py
> +        self.assertEqual(transform_error, True, "Exception raised")
Done

2022-07-27 10:43 UTC, rdeshmukh15 commented on tests/unittests/test_data_transforming.py
>          self.assertEqual(transform_error, False, "Exception raised")
Done

2022-07-27 10:44 UTC, rdeshmukh15 commented on tests/unittests/test_data_transforming.py
> +    """
Done

2022-07-27 10:45 UTC, rdeshmukh15 commented on tests/unittests/test_data_transforming.py
> +                raise TypeError('Can not by stringified')
Updated the complete test case and validated the external_product_id extracted from the URL.

2022-07-27 10:45 UTC, rdeshmukh15 commented on tap_yotpo/streams.py
> +            """
Done

2022-07-27 17:49 UTC, luandy64 commented on tests/unittests/test_stream_changes.py
> +    def test_sync_of_paginated_class_with_unsubscribe_data_with_empty_id(self,mock_transform, mock_on_batch_complete,mock_records_with_empty_id,mock_get_params, mock_to_map):
@rdeshmukh15 Sorry I should have been clearer. Add the spaces to this line and 39. But add it between all of the variables

2022-07-28 05:44 UTC, rdeshmukh15 commented on tests/unittests/test_stream_changes.py
> +    def test_sync_of_paginated_class_with_unsubscribe_data_with_empty_id(self,mock_transform, mock_on_batch_complete,mock_records_with_empty_id,mock_get_params, mock_to_map):
done

2022-07-28 13:42 UTC, luandy64 approved these changes

2022-08-01 10:50 UTC, RushiT0122 approved these changes

2022-11-10 17:29 UTC, sgandhi1311 commented
Closing this PR. As these code changes are included in other PR - https://github.com/singer-io/tap-yotpo/pull/46

2022-11-10 17:29 UTC, closed without merging